spring:
  profiles:
    active: local

# Infos Build
info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@

# Logging
logging:
  path: /srv/spring-boot-admin/log/

# Management
management:
  address: ${server.address}
  port: ${server.port}
  context-path: /manage
  info:
     git:
       mode: full

server:
  port: 8081
  context-path: /spring-boot-admin
  address: localhost

security:
  user:
    name: user
    password: Welcome1_
  boot:
    admin:
      discovery:
        converter:
          management-context-path: /manage

#needs to be set on server (e.g. in file /srv/myhelsana-test/conf/application-test.properties) or by using config server
#spring:
#  cloud:
#    discovery:
#      client:
#        simple:
#          instances:
#            myhelsana-api-gateway[0]:
#              uri: http://localhost:8080/manage/
#              metadata:
#                user:
#                  name: user
#                  password: Welcome1_