# Infos Build
info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@

# Logging
logging:
  path: /srv/spring-boot-admin/log/

# Management
management:
  address: ${server.address}
  port: ${server.port}
  context-path: /manage
  info:
     git:
       mode: full

server:
  port: 8081
  context-path: /spring-boot-admin
  address: localhost

security:
  user:
    name: user
    password: Welcome1_

# needs to be set on server (e.g. in file /srv/clearview-test/conf/application-test.properties)
# or by using config server
#spring:
#  cloud:
#    discovery:
#      client:
#        simple:
#          instances:
#            prod[0]:
#              uri: http://localhost:8080/offer-ug
#              metadata:
#                user:
#                  name: user
#                  password: Welcome1_
  boot:
    admin:
      discovery:
        converter:
          management-context-path: /manage